[Icon Theme]
Name=Adwaita Local
Comment=
Inherits=Adwaita,hicolor
Example=folder

# Directory list
Directories=symbolic/apps,scalable/apps,scalable/devices,scalable/mimes,scalable/places,scalable/status,symbolic/actions,symbolic/categories,symbolic/devices,symbolic/emblems,symbolic/mimes,symbolic/places,symbolic/status
[symbolic/apps]
Context=Applications
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Applications
Size=48
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimes]
Context=MimeTypes
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/actions]
Context=Actions
Size=16
MinSize=16
MaxSize=512
Type=Scalable



[symbolic/categories]
Context=Categories
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/devices]
Context=Devices
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/emblems]
Context=Emblems
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/mimes]
Context=MimeTypes
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/places]
Context=Places
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/status]
Context=Status
Size=16
MinSize=16
MaxSize=512
Type=Scalable



