build:
	sassc gnome-shell.scss gnome-shell.css

install:
	mkdir -p ~/.local/share/themes/gnome-shell-light-variant/gnome-shell && cp gnome-shell.css ~/.local/share/themes/gnome-shell-light-variant/gnome-shell/
